### ISSUE TITLE
Create a search capability

### ISSUE THREAD

**Issue by masteret** [tweetcity/cs373-idb#46]
The result of a search must be a list of links to crises and/or organizations and/or people (e.g. like Google).
The search results must be contextualized and the search terms must show up.
The search results must be clickable.
Multi-word search must show clearly marked and results followed by or results.

**Comment by cschwendiman** [comment]
I think this should be easier than we thought since we don't have to worry about contextualizing anything. We don't have any full text attributes... A contextual result from a tweet is just the whole tweet lol.

So our search result would be like:
{
tweets: (return tweet query with "text LIKE "%query%" OR username LIKE "%query%"),
hashtags: (return hashtag query with "text LIKE "%query%"),
locations: (return location query with city LIKE ... OR state LIKE ... OR country LIKE..)
}

With some stuff added to the queries to allow for like multiple keywords I guess. I don't think a library is necessary though since we don't need full text search.

**Comment by masteret** [comment]
Referencing http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-x-full-text-search

**Comment by masteret** [comment]
Basically finished, extra fancy functionalities may add in the future as a plus
